kind: Deployment
apiVersion: apps/v1
metadata:
  name: agautam-vision
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agautam-vision
  template:
    metadata:
      labels:
        app: agautam-vision
    spec:
      containers:
        - name: agautam-vision
          image: gcr.io/agautam-vision/agautam-vision
          ports:
          - containerPort: 80
